# Generated by Django 5.1.1 on 2024-11-06 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_voca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='lessons',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='learn_voca.lesson'),
        ),
    ]
