# Generated by Django 5.1.1 on 2024-10-24 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_test_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='lesson_id',
            new_name='lesson',
        ),
    ]
