# Generated by Django 5.1.1 on 2024-10-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_rename_lesson_id_topic_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
        migrations.AddField(
            model_name='question',
            name='tests',
            field=models.ManyToManyField(related_name='questions', to='lessons.test'),
        ),
    ]
